package com.contact.contact;

import com.contact.accessingdatamysql.entity.Contact;
import com.contact.accessingdatamysql.repository.ContactRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import com.contact.accessingdatamysql.config.ContactConfig;

import java.util.List;

@SpringBootApplication
//@EntityScan("com.contact.accessingdatamysql.entity.Contact")
//@EnableJpaRepositories("com.contact.accessingdatamysql")
public class ContactApplication {


	private static final Logger log = LoggerFactory.getLogger(ContactApplication.class);

	public static void main(String[] args) {
		SpringApplication.run(ContactApplication.class);
	}

	//@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	ContactRepository repository = ContactConfig.contactRepository();


	public void demo(ContactRepository repository) {


	}

}